import 'package:flutter/widgets.dart';
import 'package:flutter_svg/flutter_svg.dart';

import 'app_icon.dart';

// THIS FILE IS AUTO-GENERATED by flutter_icons_generator.py

class AppIconSearch extends StatelessWidget implements AppIcon {
  final double? height;
  final double? width;
  final Color? color;

  static const _svgString = '''
	<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M11 20C15.9706 20 20 15.9706 20 11C20 6.02944 15.9706 2 11 2C6.02944 2 2 6.02944 2 11C2 15.9706 6.02944 20 11 20Z" stroke="#1463F5" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><path d="M18.9299 20.6898C19.4599 22.2898 20.6699 22.4498 21.5999 21.0498C22.4499 19.7698 21.8899 18.7198 20.3499 18.7198C19.2099 18.7098 18.5699 19.5998 18.9299 20.6898Z" stroke="#1463F5" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
    ''';

  const AppIconSearch({
    super.key,
    this.height,
    this.width,
    this.color,
  });

  @override
  Widget build(BuildContext context) {
    return SvgPicture.string(
      _svgString,
      color: color,
      height: height,
      width: width,
    );
  }
}

    