import 'package:flutter/widgets.dart';
import 'package:flutter_svg/flutter_svg.dart';

import 'app_icon.dart';

// THIS FILE IS AUTO-GENERATED by flutter_icons_generator.py

class AppIconFavoriteActive extends StatelessWidget implements AppIcon {
  final double? height;
  final double? width;
  final Color? color;

  static const _svgString = '''
	<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M13.7289 3.4325L15.4889 6.9525C15.7289 7.4425 16.3689 7.9125 16.9089 8.0025L20.0989 8.5325C22.1389 8.8725 22.6189 10.3525 21.1489 11.8125L18.6689 14.2925C18.2489 14.7125 18.0189 15.5225 18.1489 16.1025L18.8589 19.1725C19.4189 21.6025 18.1289 22.5425 15.9789 21.2725L12.9889 19.5025C12.4489 19.1825 11.5589 19.1825 11.0089 19.5025L8.01893 21.2725C5.87893 22.5425 4.57893 21.5925 5.13893 19.1725L5.84893 16.1025C5.97893 15.5225 5.74893 14.7125 5.32893 14.2925L2.84893 11.8125C1.38893 10.3525 1.85893 8.8725 3.89893 8.5325L7.08893 8.0025C7.61893 7.9125 8.25893 7.4425 8.49893 6.9525L10.2589 3.4325C11.2189 1.5225 12.7789 1.5225 13.7289 3.4325Z" fill="#F9F9F9"/></svg>
    ''';

  const AppIconFavoriteActive({
    super.key,
    this.height,
    this.width,
    this.color,
  });

  @override
  Widget build(BuildContext context) {
    return SvgPicture.string(
      _svgString,
      color: color,
      height: height,
      width: width,
    );
  }
}

    