name: github_search
description: Search by github repositories.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  injectable: ^2.1.1
  get_it: ^7.6.0
  flutter_svg: ^2.0.9
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.3

  app_http_client:
    path: ./modules/app_http_client

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  injectable_generator: ^2.1.6
  provider: ^6.0.0
  json_serializable: ^6.2.1

flutter:
  uses-material-design: true

  fonts:
    - family: Main
      fonts:
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
    - family: Body
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
